--
-- PostgreSQL database dump
--

\restrict eQqje2zb5YUZXekdfLTc5bDgNglA8XhVT0cxl1QMeFaEGwDJXdWhHEEBnBjQ3Ag

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: employees_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees_employee (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    apellido character varying(100) NOT NULL,
    cedula character varying(20) NOT NULL,
    cargo character varying(150) NOT NULL,
    departamento character varying(150) NOT NULL,
    telefono character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    activo boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.employees_employee OWNER TO postgres;

--
-- Name: employees_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employees_employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment_equipment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipment_equipment (
    id bigint NOT NULL,
    codigo_patrimonial character varying(50) NOT NULL,
    marca character varying(100) NOT NULL,
    modelo character varying(100) NOT NULL,
    numero_serie character varying(100) NOT NULL,
    estado character varying(20) NOT NULL,
    ubicacion character varying(200) NOT NULL,
    observaciones text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    categoria_id bigint NOT NULL
);


ALTER TABLE public.equipment_equipment OWNER TO postgres;

--
-- Name: equipment_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipment_equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment_equipmentcategory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipment_equipmentcategory (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text NOT NULL
);


ALTER TABLE public.equipment_equipmentcategory OWNER TO postgres;

--
-- Name: equipment_equipmentcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipment_equipmentcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_equipmentcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forms_asignacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms_asignacion (
    id bigint NOT NULL,
    codigo character varying(50) NOT NULL,
    fecha_asignacion date NOT NULL,
    motivo text NOT NULL,
    observaciones text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.forms_asignacion OWNER TO postgres;

--
-- Name: forms_asignacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms_asignacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_asignacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forms_asignaciondetalle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms_asignaciondetalle (
    id bigint NOT NULL,
    estado_entrega character varying(20) NOT NULL,
    observaciones text NOT NULL,
    asignacion_id bigint NOT NULL,
    equipment_id bigint NOT NULL
);


ALTER TABLE public.forms_asignaciondetalle OWNER TO postgres;

--
-- Name: forms_asignaciondetalle_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms_asignaciondetalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_asignaciondetalle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forms_devolucion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms_devolucion (
    id bigint NOT NULL,
    codigo character varying(50) NOT NULL,
    fecha_devolucion date NOT NULL,
    observaciones text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    asignacion_id bigint,
    created_by_id integer NOT NULL,
    employee_id bigint NOT NULL,
    prestamo_id bigint
);


ALTER TABLE public.forms_devolucion OWNER TO postgres;

--
-- Name: forms_devolucion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms_devolucion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_devolucion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forms_devoluciondetalle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms_devoluciondetalle (
    id bigint NOT NULL,
    estado_recibido character varying(20) NOT NULL,
    observaciones text NOT NULL,
    devolucion_id bigint NOT NULL,
    equipment_id bigint NOT NULL
);


ALTER TABLE public.forms_devoluciondetalle OWNER TO postgres;

--
-- Name: forms_devoluciondetalle_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms_devoluciondetalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_devoluciondetalle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forms_prestamo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms_prestamo (
    id bigint NOT NULL,
    codigo character varying(50) NOT NULL,
    fecha_prestamo date NOT NULL,
    fecha_prevista_devolucion date NOT NULL,
    motivo text NOT NULL,
    estado character varying(20) NOT NULL,
    observaciones text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.forms_prestamo OWNER TO postgres;

--
-- Name: forms_prestamo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms_prestamo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_prestamo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forms_prestamodetalle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms_prestamodetalle (
    id bigint NOT NULL,
    estado_entrega character varying(20) NOT NULL,
    fecha_devolucion date,
    estado_devolucion character varying(20),
    observaciones_devolucion text NOT NULL,
    equipment_id bigint NOT NULL,
    prestamo_id bigint NOT NULL
);


ALTER TABLE public.forms_prestamodetalle OWNER TO postgres;

--
-- Name: forms_prestamodetalle_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms_prestamodetalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_prestamodetalle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_profile (
    id bigint NOT NULL,
    rol character varying(20) NOT NULL,
    telefono character varying(20) NOT NULL,
    area character varying(100) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.users_profile OWNER TO postgres;

--
-- Name: users_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
1	Estandar
2	Administrador
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
1	2	1
2	2	2
3	2	3
4	2	4
5	2	5
6	2	6
7	2	7
8	2	8
9	2	9
10	2	10
11	2	11
12	2	12
13	2	13
14	2	14
15	2	15
16	2	16
17	2	17
18	2	18
19	2	19
20	2	20
21	2	21
22	2	22
23	2	23
24	2	24
25	2	25
26	2	26
27	2	27
28	2	28
29	2	29
30	2	30
31	2	31
32	2	32
33	2	33
34	2	34
35	2	35
36	2	36
37	2	37
38	2	38
39	2	39
40	2	40
41	2	41
42	2	42
43	2	43
44	2	44
45	2	45
46	2	46
47	2	47
48	2	48
49	2	49
50	2	50
51	2	51
52	2	52
53	2	53
54	2	54
55	2	55
56	2	56
57	2	57
58	2	58
59	2	59
60	2	60
61	2	61
62	2	62
63	2	63
64	2	64
65	1	41
66	1	42
67	1	44
68	1	49
69	1	50
70	1	52
71	1	57
72	1	58
73	1	60
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Perfil	7	add_profile
26	Can change Perfil	7	change_profile
27	Can delete Perfil	7	delete_profile
28	Can view Perfil	7	view_profile
29	Can add Empleado	8	add_employee
30	Can change Empleado	8	change_employee
31	Can delete Empleado	8	delete_employee
32	Can view Empleado	8	view_employee
33	Can add Categoria de Equipo	10	add_equipmentcategory
34	Can change Categoria de Equipo	10	change_equipmentcategory
35	Can delete Categoria de Equipo	10	delete_equipmentcategory
36	Can view Categoria de Equipo	10	view_equipmentcategory
37	Can add Equipo	9	add_equipment
38	Can change Equipo	9	change_equipment
39	Can delete Equipo	9	delete_equipment
40	Can view Equipo	9	view_equipment
41	Can add Acta de Asignacion	11	add_asignacion
42	Can change Acta de Asignacion	11	change_asignacion
43	Can delete Acta de Asignacion	11	delete_asignacion
44	Can view Acta de Asignacion	11	view_asignacion
45	Can add Detalle de Asignacion	12	add_asignaciondetalle
46	Can change Detalle de Asignacion	12	change_asignaciondetalle
47	Can delete Detalle de Asignacion	12	delete_asignaciondetalle
48	Can view Detalle de Asignacion	12	view_asignaciondetalle
49	Can add Acta de Devolucion	13	add_devolucion
50	Can change Acta de Devolucion	13	change_devolucion
51	Can delete Acta de Devolucion	13	delete_devolucion
52	Can view Acta de Devolucion	13	view_devolucion
53	Can add Detalle de Devolucion	14	add_devoluciondetalle
54	Can change Detalle de Devolucion	14	change_devoluciondetalle
55	Can delete Detalle de Devolucion	14	delete_devoluciondetalle
56	Can view Detalle de Devolucion	14	view_devoluciondetalle
57	Can add Acta de Prestamo	15	add_prestamo
58	Can change Acta de Prestamo	15	change_prestamo
59	Can delete Acta de Prestamo	15	delete_prestamo
60	Can view Acta de Prestamo	15	view_prestamo
61	Can add Detalle de Prestamo	16	add_prestamodetalle
62	Can change Detalle de Prestamo	16	change_prestamodetalle
63	Can delete Detalle de Prestamo	16	delete_prestamodetalle
64	Can view Detalle de Prestamo	16	view_prestamodetalle
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$4hDbvlmkZsVxbOOXgvUKmJ$SKF47m/7Lcvy+XowEU2Guaqu1yfbgUSwSEEfDAkmxZs=	\N	t	admin			admin@example.com	t	t	2026-05-16 23:35:23.222143-05
2	pbkdf2_sha256$1200000$cm0nj7Z9kmXrfKIFL9js61$/iG6MixBHIlGmRPB6KBLJOFH/29swa/waZticnvAfCk=	\N	f	tecnico1	Juan	Perez	tecnico1@example.com	f	t	2026-05-16 23:35:36.418186-05
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
1	2	1
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	users	profile
8	employees	employee
9	equipment	equipment
10	equipment	equipmentcategory
11	forms	asignacion
12	forms	asignaciondetalle
13	forms	devolucion
14	forms	devoluciondetalle
15	forms	prestamo
16	forms	prestamodetalle
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-05-16 23:35:14.41561-05
2	auth	0001_initial	2026-05-16 23:35:14.485497-05
3	admin	0001_initial	2026-05-16 23:35:14.508934-05
4	admin	0002_logentry_remove_auto_add	2026-05-16 23:35:14.514214-05
5	admin	0003_logentry_add_action_flag_choices	2026-05-16 23:35:14.519746-05
6	contenttypes	0002_remove_content_type_name	2026-05-16 23:35:14.532376-05
7	auth	0002_alter_permission_name_max_length	2026-05-16 23:35:14.544916-05
8	auth	0003_alter_user_email_max_length	2026-05-16 23:35:14.5507-05
9	auth	0004_alter_user_username_opts	2026-05-16 23:35:14.556239-05
10	auth	0005_alter_user_last_login_null	2026-05-16 23:35:14.562812-05
11	auth	0006_require_contenttypes_0002	2026-05-16 23:35:14.563967-05
12	auth	0007_alter_validators_add_error_messages	2026-05-16 23:35:14.569811-05
13	auth	0008_alter_user_username_max_length	2026-05-16 23:35:14.585437-05
14	auth	0009_alter_user_last_name_max_length	2026-05-16 23:35:14.59283-05
15	auth	0010_alter_group_name_max_length	2026-05-16 23:35:14.599924-05
16	auth	0011_update_proxy_permissions	2026-05-16 23:35:14.604949-05
17	auth	0012_alter_user_first_name_max_length	2026-05-16 23:35:14.611255-05
18	employees	0001_initial	2026-05-16 23:35:14.622557-05
19	equipment	0001_initial	2026-05-16 23:35:14.648651-05
20	forms	0001_initial	2026-05-16 23:35:14.793672-05
21	sessions	0001_initial	2026-05-16 23:35:14.804009-05
22	users	0001_initial	2026-05-16 23:35:14.831137-05
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: employees_employee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employees_employee (id, nombre, apellido, cedula, cargo, departamento, telefono, email, activo, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: equipment_equipment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.equipment_equipment (id, codigo_patrimonial, marca, modelo, numero_serie, estado, ubicacion, observaciones, created_at, updated_at, categoria_id) FROM stdin;
\.


--
-- Data for Name: equipment_equipmentcategory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.equipment_equipmentcategory (id, nombre, descripcion) FROM stdin;
\.


--
-- Data for Name: forms_asignacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.forms_asignacion (id, codigo, fecha_asignacion, motivo, observaciones, created_at, updated_at, created_by_id, employee_id) FROM stdin;
\.


--
-- Data for Name: forms_asignaciondetalle; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.forms_asignaciondetalle (id, estado_entrega, observaciones, asignacion_id, equipment_id) FROM stdin;
\.


--
-- Data for Name: forms_devolucion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.forms_devolucion (id, codigo, fecha_devolucion, observaciones, created_at, updated_at, asignacion_id, created_by_id, employee_id, prestamo_id) FROM stdin;
\.


--
-- Data for Name: forms_devoluciondetalle; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.forms_devoluciondetalle (id, estado_recibido, observaciones, devolucion_id, equipment_id) FROM stdin;
\.


--
-- Data for Name: forms_prestamo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.forms_prestamo (id, codigo, fecha_prestamo, fecha_prevista_devolucion, motivo, estado, observaciones, created_at, updated_at, created_by_id, employee_id) FROM stdin;
\.


--
-- Data for Name: forms_prestamodetalle; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.forms_prestamodetalle (id, estado_entrega, fecha_devolucion, estado_devolucion, observaciones_devolucion, equipment_id, prestamo_id) FROM stdin;
\.


--
-- Data for Name: users_profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_profile (id, rol, telefono, area, user_id) FROM stdin;
1	standard			1
2	standard			2
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 2, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 73, true);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 64, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, true);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 16, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 22, true);


--
-- Name: employees_employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employees_employee_id_seq', 1, false);


--
-- Name: equipment_equipment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.equipment_equipment_id_seq', 1, false);


--
-- Name: equipment_equipmentcategory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.equipment_equipmentcategory_id_seq', 1, false);


--
-- Name: forms_asignacion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.forms_asignacion_id_seq', 1, false);


--
-- Name: forms_asignaciondetalle_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.forms_asignaciondetalle_id_seq', 1, false);


--
-- Name: forms_devolucion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.forms_devolucion_id_seq', 1, false);


--
-- Name: forms_devoluciondetalle_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.forms_devoluciondetalle_id_seq', 1, false);


--
-- Name: forms_prestamo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.forms_prestamo_id_seq', 1, false);


--
-- Name: forms_prestamodetalle_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.forms_prestamodetalle_id_seq', 1, false);


--
-- Name: users_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_profile_id_seq', 2, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: employees_employee employees_employee_cedula_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees_employee
    ADD CONSTRAINT employees_employee_cedula_key UNIQUE (cedula);


--
-- Name: employees_employee employees_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees_employee
    ADD CONSTRAINT employees_employee_pkey PRIMARY KEY (id);


--
-- Name: equipment_equipment equipment_equipment_codigo_patrimonial_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_equipment
    ADD CONSTRAINT equipment_equipment_codigo_patrimonial_key UNIQUE (codigo_patrimonial);


--
-- Name: equipment_equipment equipment_equipment_numero_serie_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_equipment
    ADD CONSTRAINT equipment_equipment_numero_serie_key UNIQUE (numero_serie);


--
-- Name: equipment_equipment equipment_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_equipment
    ADD CONSTRAINT equipment_equipment_pkey PRIMARY KEY (id);


--
-- Name: equipment_equipmentcategory equipment_equipmentcategory_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_equipmentcategory
    ADD CONSTRAINT equipment_equipmentcategory_nombre_key UNIQUE (nombre);


--
-- Name: equipment_equipmentcategory equipment_equipmentcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_equipmentcategory
    ADD CONSTRAINT equipment_equipmentcategory_pkey PRIMARY KEY (id);


--
-- Name: forms_asignacion forms_asignacion_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignacion
    ADD CONSTRAINT forms_asignacion_codigo_key UNIQUE (codigo);


--
-- Name: forms_asignacion forms_asignacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignacion
    ADD CONSTRAINT forms_asignacion_pkey PRIMARY KEY (id);


--
-- Name: forms_asignaciondetalle forms_asignaciondetalle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignaciondetalle
    ADD CONSTRAINT forms_asignaciondetalle_pkey PRIMARY KEY (id);


--
-- Name: forms_devolucion forms_devolucion_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devolucion
    ADD CONSTRAINT forms_devolucion_codigo_key UNIQUE (codigo);


--
-- Name: forms_devolucion forms_devolucion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devolucion
    ADD CONSTRAINT forms_devolucion_pkey PRIMARY KEY (id);


--
-- Name: forms_devoluciondetalle forms_devoluciondetalle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devoluciondetalle
    ADD CONSTRAINT forms_devoluciondetalle_pkey PRIMARY KEY (id);


--
-- Name: forms_prestamo forms_prestamo_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamo
    ADD CONSTRAINT forms_prestamo_codigo_key UNIQUE (codigo);


--
-- Name: forms_prestamo forms_prestamo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamo
    ADD CONSTRAINT forms_prestamo_pkey PRIMARY KEY (id);


--
-- Name: forms_prestamodetalle forms_prestamodetalle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamodetalle
    ADD CONSTRAINT forms_prestamodetalle_pkey PRIMARY KEY (id);


--
-- Name: users_profile users_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_pkey PRIMARY KEY (id);


--
-- Name: users_profile users_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: employees_employee_cedula_5eeb74b7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employees_employee_cedula_5eeb74b7_like ON public.employees_employee USING btree (cedula varchar_pattern_ops);


--
-- Name: equipment_equipment_categoria_id_2c347081; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX equipment_equipment_categoria_id_2c347081 ON public.equipment_equipment USING btree (categoria_id);


--
-- Name: equipment_equipment_codigo_patrimonial_f45f4755_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX equipment_equipment_codigo_patrimonial_f45f4755_like ON public.equipment_equipment USING btree (codigo_patrimonial varchar_pattern_ops);


--
-- Name: equipment_equipment_numero_serie_a215921d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX equipment_equipment_numero_serie_a215921d_like ON public.equipment_equipment USING btree (numero_serie varchar_pattern_ops);


--
-- Name: equipment_equipmentcategory_nombre_7feb8128_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX equipment_equipmentcategory_nombre_7feb8128_like ON public.equipment_equipmentcategory USING btree (nombre varchar_pattern_ops);


--
-- Name: forms_asignacion_codigo_9978f6ab_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_asignacion_codigo_9978f6ab_like ON public.forms_asignacion USING btree (codigo varchar_pattern_ops);


--
-- Name: forms_asignacion_created_by_id_893e9c70; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_asignacion_created_by_id_893e9c70 ON public.forms_asignacion USING btree (created_by_id);


--
-- Name: forms_asignacion_employee_id_bbdbe2de; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_asignacion_employee_id_bbdbe2de ON public.forms_asignacion USING btree (employee_id);


--
-- Name: forms_asignaciondetalle_asignacion_id_2627b4d7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_asignaciondetalle_asignacion_id_2627b4d7 ON public.forms_asignaciondetalle USING btree (asignacion_id);


--
-- Name: forms_asignaciondetalle_equipment_id_7822ad68; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_asignaciondetalle_equipment_id_7822ad68 ON public.forms_asignaciondetalle USING btree (equipment_id);


--
-- Name: forms_devolucion_asignacion_id_fc4df71c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devolucion_asignacion_id_fc4df71c ON public.forms_devolucion USING btree (asignacion_id);


--
-- Name: forms_devolucion_codigo_b27d01c2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devolucion_codigo_b27d01c2_like ON public.forms_devolucion USING btree (codigo varchar_pattern_ops);


--
-- Name: forms_devolucion_created_by_id_1096db80; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devolucion_created_by_id_1096db80 ON public.forms_devolucion USING btree (created_by_id);


--
-- Name: forms_devolucion_employee_id_a8517878; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devolucion_employee_id_a8517878 ON public.forms_devolucion USING btree (employee_id);


--
-- Name: forms_devolucion_prestamo_id_08df15de; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devolucion_prestamo_id_08df15de ON public.forms_devolucion USING btree (prestamo_id);


--
-- Name: forms_devoluciondetalle_devolucion_id_280b1b50; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devoluciondetalle_devolucion_id_280b1b50 ON public.forms_devoluciondetalle USING btree (devolucion_id);


--
-- Name: forms_devoluciondetalle_equipment_id_866932a8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devoluciondetalle_equipment_id_866932a8 ON public.forms_devoluciondetalle USING btree (equipment_id);


--
-- Name: forms_prestamo_codigo_8c53933c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_prestamo_codigo_8c53933c_like ON public.forms_prestamo USING btree (codigo varchar_pattern_ops);


--
-- Name: forms_prestamo_created_by_id_b6e3a665; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_prestamo_created_by_id_b6e3a665 ON public.forms_prestamo USING btree (created_by_id);


--
-- Name: forms_prestamo_employee_id_fbc1037c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_prestamo_employee_id_fbc1037c ON public.forms_prestamo USING btree (employee_id);


--
-- Name: forms_prestamodetalle_equipment_id_405eb8fd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_prestamodetalle_equipment_id_405eb8fd ON public.forms_prestamodetalle USING btree (equipment_id);


--
-- Name: forms_prestamodetalle_prestamo_id_c0ed8daa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_prestamodetalle_prestamo_id_c0ed8daa ON public.forms_prestamodetalle USING btree (prestamo_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: equipment_equipment equipment_equipment_categoria_id_2c347081_fk_equipment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_equipment
    ADD CONSTRAINT equipment_equipment_categoria_id_2c347081_fk_equipment FOREIGN KEY (categoria_id) REFERENCES public.equipment_equipmentcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_asignacion forms_asignacion_created_by_id_893e9c70_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignacion
    ADD CONSTRAINT forms_asignacion_created_by_id_893e9c70_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_asignacion forms_asignacion_employee_id_bbdbe2de_fk_employees_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignacion
    ADD CONSTRAINT forms_asignacion_employee_id_bbdbe2de_fk_employees_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_asignaciondetalle forms_asignaciondeta_asignacion_id_2627b4d7_fk_forms_asi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignaciondetalle
    ADD CONSTRAINT forms_asignaciondeta_asignacion_id_2627b4d7_fk_forms_asi FOREIGN KEY (asignacion_id) REFERENCES public.forms_asignacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_asignaciondetalle forms_asignaciondeta_equipment_id_7822ad68_fk_equipment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignaciondetalle
    ADD CONSTRAINT forms_asignaciondeta_equipment_id_7822ad68_fk_equipment FOREIGN KEY (equipment_id) REFERENCES public.equipment_equipment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_devolucion forms_devolucion_asignacion_id_fc4df71c_fk_forms_asignacion_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devolucion
    ADD CONSTRAINT forms_devolucion_asignacion_id_fc4df71c_fk_forms_asignacion_id FOREIGN KEY (asignacion_id) REFERENCES public.forms_asignacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_devolucion forms_devolucion_created_by_id_1096db80_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devolucion
    ADD CONSTRAINT forms_devolucion_created_by_id_1096db80_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_devolucion forms_devolucion_employee_id_a8517878_fk_employees_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devolucion
    ADD CONSTRAINT forms_devolucion_employee_id_a8517878_fk_employees_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_devolucion forms_devolucion_prestamo_id_08df15de_fk_forms_prestamo_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devolucion
    ADD CONSTRAINT forms_devolucion_prestamo_id_08df15de_fk_forms_prestamo_id FOREIGN KEY (prestamo_id) REFERENCES public.forms_prestamo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_devoluciondetalle forms_devoluciondeta_devolucion_id_280b1b50_fk_forms_dev; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devoluciondetalle
    ADD CONSTRAINT forms_devoluciondeta_devolucion_id_280b1b50_fk_forms_dev FOREIGN KEY (devolucion_id) REFERENCES public.forms_devolucion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_devoluciondetalle forms_devoluciondeta_equipment_id_866932a8_fk_equipment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devoluciondetalle
    ADD CONSTRAINT forms_devoluciondeta_equipment_id_866932a8_fk_equipment FOREIGN KEY (equipment_id) REFERENCES public.equipment_equipment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_prestamo forms_prestamo_created_by_id_b6e3a665_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamo
    ADD CONSTRAINT forms_prestamo_created_by_id_b6e3a665_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_prestamo forms_prestamo_employee_id_fbc1037c_fk_employees_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamo
    ADD CONSTRAINT forms_prestamo_employee_id_fbc1037c_fk_employees_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_prestamodetalle forms_prestamodetall_equipment_id_405eb8fd_fk_equipment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamodetalle
    ADD CONSTRAINT forms_prestamodetall_equipment_id_405eb8fd_fk_equipment FOREIGN KEY (equipment_id) REFERENCES public.equipment_equipment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_prestamodetalle forms_prestamodetalle_prestamo_id_c0ed8daa_fk_forms_prestamo_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamodetalle
    ADD CONSTRAINT forms_prestamodetalle_prestamo_id_c0ed8daa_fk_forms_prestamo_id FOREIGN KEY (prestamo_id) REFERENCES public.forms_prestamo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_profile users_profile_user_id_2112e78d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_user_id_2112e78d_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict eQqje2zb5YUZXekdfLTc5bDgNglA8XhVT0cxl1QMeFaEGwDJXdWhHEEBnBjQ3Ag

