--
-- PostgreSQL database dump
--

\restrict saXRpvCnHYVFMWpi5b35dIQlN0AG4sZl1Me5SnymYkP2XyNzgKvnHpadTlj9pyo

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: employees_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees_employee (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    apellido character varying(100) NOT NULL,
    cedula character varying(20) NOT NULL,
    cargo character varying(150) NOT NULL,
    departamento character varying(150) NOT NULL,
    telefono character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    activo boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.employees_employee OWNER TO postgres;

--
-- Name: employees_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employees_employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment_equipment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipment_equipment (
    id bigint NOT NULL,
    codigo_patrimonial character varying(50) NOT NULL,
    marca character varying(100) NOT NULL,
    modelo character varying(100) NOT NULL,
    numero_serie character varying(100) NOT NULL,
    estado character varying(20) NOT NULL,
    ubicacion character varying(200) NOT NULL,
    observaciones text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    categoria_id bigint NOT NULL
);


ALTER TABLE public.equipment_equipment OWNER TO postgres;

--
-- Name: equipment_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipment_equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: equipment_equipmentcategory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.equipment_equipmentcategory (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text NOT NULL
);


ALTER TABLE public.equipment_equipmentcategory OWNER TO postgres;

--
-- Name: equipment_equipmentcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.equipment_equipmentcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_equipmentcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forms_asignacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms_asignacion (
    id bigint NOT NULL,
    codigo character varying(50) NOT NULL,
    fecha_asignacion date NOT NULL,
    motivo text NOT NULL,
    observaciones text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.forms_asignacion OWNER TO postgres;

--
-- Name: forms_asignacion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms_asignacion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_asignacion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forms_asignaciondetalle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms_asignaciondetalle (
    id bigint NOT NULL,
    estado_entrega character varying(20) NOT NULL,
    observaciones text NOT NULL,
    asignacion_id bigint NOT NULL,
    equipment_id bigint NOT NULL
);


ALTER TABLE public.forms_asignaciondetalle OWNER TO postgres;

--
-- Name: forms_asignaciondetalle_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms_asignaciondetalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_asignaciondetalle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forms_devolucion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms_devolucion (
    id bigint NOT NULL,
    codigo character varying(50) NOT NULL,
    fecha_devolucion date NOT NULL,
    observaciones text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    asignacion_id bigint,
    created_by_id integer NOT NULL,
    employee_id bigint NOT NULL,
    prestamo_id bigint
);


ALTER TABLE public.forms_devolucion OWNER TO postgres;

--
-- Name: forms_devolucion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms_devolucion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_devolucion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forms_devoluciondetalle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms_devoluciondetalle (
    id bigint NOT NULL,
    estado_recibido character varying(20) NOT NULL,
    observaciones text NOT NULL,
    devolucion_id bigint NOT NULL,
    equipment_id bigint NOT NULL
);


ALTER TABLE public.forms_devoluciondetalle OWNER TO postgres;

--
-- Name: forms_devoluciondetalle_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms_devoluciondetalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_devoluciondetalle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forms_prestamo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms_prestamo (
    id bigint NOT NULL,
    codigo character varying(50) NOT NULL,
    fecha_prestamo date NOT NULL,
    fecha_prevista_devolucion date NOT NULL,
    motivo text NOT NULL,
    estado character varying(20) NOT NULL,
    observaciones text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id integer NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.forms_prestamo OWNER TO postgres;

--
-- Name: forms_prestamo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms_prestamo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_prestamo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forms_prestamodetalle; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forms_prestamodetalle (
    id bigint NOT NULL,
    estado_entrega character varying(20) NOT NULL,
    fecha_devolucion date,
    estado_devolucion character varying(20),
    observaciones_devolucion text NOT NULL,
    equipment_id bigint NOT NULL,
    prestamo_id bigint NOT NULL
);


ALTER TABLE public.forms_prestamodetalle OWNER TO postgres;

--
-- Name: forms_prestamodetalle_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forms_prestamodetalle ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forms_prestamodetalle_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_profile (
    id bigint NOT NULL,
    rol character varying(20) NOT NULL,
    telefono character varying(20) NOT NULL,
    area character varying(100) NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.users_profile OWNER TO postgres;

--
-- Name: users_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: employees_employee employees_employee_cedula_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees_employee
    ADD CONSTRAINT employees_employee_cedula_key UNIQUE (cedula);


--
-- Name: employees_employee employees_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees_employee
    ADD CONSTRAINT employees_employee_pkey PRIMARY KEY (id);


--
-- Name: equipment_equipment equipment_equipment_codigo_patrimonial_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_equipment
    ADD CONSTRAINT equipment_equipment_codigo_patrimonial_key UNIQUE (codigo_patrimonial);


--
-- Name: equipment_equipment equipment_equipment_numero_serie_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_equipment
    ADD CONSTRAINT equipment_equipment_numero_serie_key UNIQUE (numero_serie);


--
-- Name: equipment_equipment equipment_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_equipment
    ADD CONSTRAINT equipment_equipment_pkey PRIMARY KEY (id);


--
-- Name: equipment_equipmentcategory equipment_equipmentcategory_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_equipmentcategory
    ADD CONSTRAINT equipment_equipmentcategory_nombre_key UNIQUE (nombre);


--
-- Name: equipment_equipmentcategory equipment_equipmentcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_equipmentcategory
    ADD CONSTRAINT equipment_equipmentcategory_pkey PRIMARY KEY (id);


--
-- Name: forms_asignacion forms_asignacion_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignacion
    ADD CONSTRAINT forms_asignacion_codigo_key UNIQUE (codigo);


--
-- Name: forms_asignacion forms_asignacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignacion
    ADD CONSTRAINT forms_asignacion_pkey PRIMARY KEY (id);


--
-- Name: forms_asignaciondetalle forms_asignaciondetalle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignaciondetalle
    ADD CONSTRAINT forms_asignaciondetalle_pkey PRIMARY KEY (id);


--
-- Name: forms_devolucion forms_devolucion_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devolucion
    ADD CONSTRAINT forms_devolucion_codigo_key UNIQUE (codigo);


--
-- Name: forms_devolucion forms_devolucion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devolucion
    ADD CONSTRAINT forms_devolucion_pkey PRIMARY KEY (id);


--
-- Name: forms_devoluciondetalle forms_devoluciondetalle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devoluciondetalle
    ADD CONSTRAINT forms_devoluciondetalle_pkey PRIMARY KEY (id);


--
-- Name: forms_prestamo forms_prestamo_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamo
    ADD CONSTRAINT forms_prestamo_codigo_key UNIQUE (codigo);


--
-- Name: forms_prestamo forms_prestamo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamo
    ADD CONSTRAINT forms_prestamo_pkey PRIMARY KEY (id);


--
-- Name: forms_prestamodetalle forms_prestamodetalle_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamodetalle
    ADD CONSTRAINT forms_prestamodetalle_pkey PRIMARY KEY (id);


--
-- Name: users_profile users_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_pkey PRIMARY KEY (id);


--
-- Name: users_profile users_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: employees_employee_cedula_5eeb74b7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX employees_employee_cedula_5eeb74b7_like ON public.employees_employee USING btree (cedula varchar_pattern_ops);


--
-- Name: equipment_equipment_categoria_id_2c347081; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX equipment_equipment_categoria_id_2c347081 ON public.equipment_equipment USING btree (categoria_id);


--
-- Name: equipment_equipment_codigo_patrimonial_f45f4755_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX equipment_equipment_codigo_patrimonial_f45f4755_like ON public.equipment_equipment USING btree (codigo_patrimonial varchar_pattern_ops);


--
-- Name: equipment_equipment_numero_serie_a215921d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX equipment_equipment_numero_serie_a215921d_like ON public.equipment_equipment USING btree (numero_serie varchar_pattern_ops);


--
-- Name: equipment_equipmentcategory_nombre_7feb8128_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX equipment_equipmentcategory_nombre_7feb8128_like ON public.equipment_equipmentcategory USING btree (nombre varchar_pattern_ops);


--
-- Name: forms_asignacion_codigo_9978f6ab_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_asignacion_codigo_9978f6ab_like ON public.forms_asignacion USING btree (codigo varchar_pattern_ops);


--
-- Name: forms_asignacion_created_by_id_893e9c70; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_asignacion_created_by_id_893e9c70 ON public.forms_asignacion USING btree (created_by_id);


--
-- Name: forms_asignacion_employee_id_bbdbe2de; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_asignacion_employee_id_bbdbe2de ON public.forms_asignacion USING btree (employee_id);


--
-- Name: forms_asignaciondetalle_asignacion_id_2627b4d7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_asignaciondetalle_asignacion_id_2627b4d7 ON public.forms_asignaciondetalle USING btree (asignacion_id);


--
-- Name: forms_asignaciondetalle_equipment_id_7822ad68; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_asignaciondetalle_equipment_id_7822ad68 ON public.forms_asignaciondetalle USING btree (equipment_id);


--
-- Name: forms_devolucion_asignacion_id_fc4df71c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devolucion_asignacion_id_fc4df71c ON public.forms_devolucion USING btree (asignacion_id);


--
-- Name: forms_devolucion_codigo_b27d01c2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devolucion_codigo_b27d01c2_like ON public.forms_devolucion USING btree (codigo varchar_pattern_ops);


--
-- Name: forms_devolucion_created_by_id_1096db80; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devolucion_created_by_id_1096db80 ON public.forms_devolucion USING btree (created_by_id);


--
-- Name: forms_devolucion_employee_id_a8517878; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devolucion_employee_id_a8517878 ON public.forms_devolucion USING btree (employee_id);


--
-- Name: forms_devolucion_prestamo_id_08df15de; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devolucion_prestamo_id_08df15de ON public.forms_devolucion USING btree (prestamo_id);


--
-- Name: forms_devoluciondetalle_devolucion_id_280b1b50; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devoluciondetalle_devolucion_id_280b1b50 ON public.forms_devoluciondetalle USING btree (devolucion_id);


--
-- Name: forms_devoluciondetalle_equipment_id_866932a8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_devoluciondetalle_equipment_id_866932a8 ON public.forms_devoluciondetalle USING btree (equipment_id);


--
-- Name: forms_prestamo_codigo_8c53933c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_prestamo_codigo_8c53933c_like ON public.forms_prestamo USING btree (codigo varchar_pattern_ops);


--
-- Name: forms_prestamo_created_by_id_b6e3a665; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_prestamo_created_by_id_b6e3a665 ON public.forms_prestamo USING btree (created_by_id);


--
-- Name: forms_prestamo_employee_id_fbc1037c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_prestamo_employee_id_fbc1037c ON public.forms_prestamo USING btree (employee_id);


--
-- Name: forms_prestamodetalle_equipment_id_405eb8fd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_prestamodetalle_equipment_id_405eb8fd ON public.forms_prestamodetalle USING btree (equipment_id);


--
-- Name: forms_prestamodetalle_prestamo_id_c0ed8daa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX forms_prestamodetalle_prestamo_id_c0ed8daa ON public.forms_prestamodetalle USING btree (prestamo_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: equipment_equipment equipment_equipment_categoria_id_2c347081_fk_equipment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.equipment_equipment
    ADD CONSTRAINT equipment_equipment_categoria_id_2c347081_fk_equipment FOREIGN KEY (categoria_id) REFERENCES public.equipment_equipmentcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_asignacion forms_asignacion_created_by_id_893e9c70_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignacion
    ADD CONSTRAINT forms_asignacion_created_by_id_893e9c70_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_asignacion forms_asignacion_employee_id_bbdbe2de_fk_employees_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignacion
    ADD CONSTRAINT forms_asignacion_employee_id_bbdbe2de_fk_employees_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_asignaciondetalle forms_asignaciondeta_asignacion_id_2627b4d7_fk_forms_asi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignaciondetalle
    ADD CONSTRAINT forms_asignaciondeta_asignacion_id_2627b4d7_fk_forms_asi FOREIGN KEY (asignacion_id) REFERENCES public.forms_asignacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_asignaciondetalle forms_asignaciondeta_equipment_id_7822ad68_fk_equipment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_asignaciondetalle
    ADD CONSTRAINT forms_asignaciondeta_equipment_id_7822ad68_fk_equipment FOREIGN KEY (equipment_id) REFERENCES public.equipment_equipment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_devolucion forms_devolucion_asignacion_id_fc4df71c_fk_forms_asignacion_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devolucion
    ADD CONSTRAINT forms_devolucion_asignacion_id_fc4df71c_fk_forms_asignacion_id FOREIGN KEY (asignacion_id) REFERENCES public.forms_asignacion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_devolucion forms_devolucion_created_by_id_1096db80_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devolucion
    ADD CONSTRAINT forms_devolucion_created_by_id_1096db80_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_devolucion forms_devolucion_employee_id_a8517878_fk_employees_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devolucion
    ADD CONSTRAINT forms_devolucion_employee_id_a8517878_fk_employees_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_devolucion forms_devolucion_prestamo_id_08df15de_fk_forms_prestamo_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devolucion
    ADD CONSTRAINT forms_devolucion_prestamo_id_08df15de_fk_forms_prestamo_id FOREIGN KEY (prestamo_id) REFERENCES public.forms_prestamo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_devoluciondetalle forms_devoluciondeta_devolucion_id_280b1b50_fk_forms_dev; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devoluciondetalle
    ADD CONSTRAINT forms_devoluciondeta_devolucion_id_280b1b50_fk_forms_dev FOREIGN KEY (devolucion_id) REFERENCES public.forms_devolucion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_devoluciondetalle forms_devoluciondeta_equipment_id_866932a8_fk_equipment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_devoluciondetalle
    ADD CONSTRAINT forms_devoluciondeta_equipment_id_866932a8_fk_equipment FOREIGN KEY (equipment_id) REFERENCES public.equipment_equipment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_prestamo forms_prestamo_created_by_id_b6e3a665_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamo
    ADD CONSTRAINT forms_prestamo_created_by_id_b6e3a665_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_prestamo forms_prestamo_employee_id_fbc1037c_fk_employees_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamo
    ADD CONSTRAINT forms_prestamo_employee_id_fbc1037c_fk_employees_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_prestamodetalle forms_prestamodetall_equipment_id_405eb8fd_fk_equipment; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamodetalle
    ADD CONSTRAINT forms_prestamodetall_equipment_id_405eb8fd_fk_equipment FOREIGN KEY (equipment_id) REFERENCES public.equipment_equipment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: forms_prestamodetalle forms_prestamodetalle_prestamo_id_c0ed8daa_fk_forms_prestamo_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forms_prestamodetalle
    ADD CONSTRAINT forms_prestamodetalle_prestamo_id_c0ed8daa_fk_forms_prestamo_id FOREIGN KEY (prestamo_id) REFERENCES public.forms_prestamo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_profile users_profile_user_id_2112e78d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_profile
    ADD CONSTRAINT users_profile_user_id_2112e78d_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict saXRpvCnHYVFMWpi5b35dIQlN0AG4sZl1Me5SnymYkP2XyNzgKvnHpadTlj9pyo

