# Generated by Django 6.0.5 on 2026-05-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('icono', models.CharField(blank=True, max_length=20, verbose_name='Icono')),
                ('url_name', models.CharField(blank=True, max_length=100, verbose_name='URL Name')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='modulos',
            field=models.ManyToManyField(blank=True, to='users.module', verbose_name='Modulos asignados'),
        ),
    ]
