# Generated by Django 6.0.5 on 2026-05-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_module_profile_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cambiar_password',
            field=models.BooleanField(default=True, help_text='Si esta activo, el usuario debera cambiar su contrasena al iniciar sesion', verbose_name='Cambiar password'),
        ),
    ]
