# Generated by Django 6.0.5 on 2026-05-17 07:39

from django.db import migrations


def add_colaboradores_module(apps, schema_editor):
    Module = apps.get_model('users', 'Module')
    Module.objects.get_or_create(
        nombre='Colaboradores',
        defaults={
            'icono': '👤',
            'url_name': 'employees:employee_list',
            'activo': True,
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_cambiar_password'),
    ]

    operations = [
        migrations.RunPython(add_colaboradores_module, migrations.RunPython.noop),
    ]
