# Generated by Django 6.0.5 on 2026-05-17 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo de Acta')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de Asignacion')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Acta de Asignacion',
                'verbose_name_plural': 'Actas de Asignacion',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_entrega', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20, verbose_name='Estado de Entrega')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='forms.asignacion', verbose_name='Asignacion')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Detalle de Asignacion',
                'verbose_name_plural': 'Detalles de Asignacion',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo de Acta')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de Devolucion')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.asignacion', verbose_name='Asignacion relacionada')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Acta de Devolucion',
                'verbose_name_plural': 'Actas de Devolucion',
                'ordering': ['-fecha_devolucion'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_recibido', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20, verbose_name='Estado Recibido')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='forms.devolucion', verbose_name='Devolucion')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Detalle de Devolucion',
                'verbose_name_plural': 'Detalles de Devolucion',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo de Acta')),
                ('fecha_prestamo', models.DateField(verbose_name='Fecha de Prestamo')),
                ('fecha_prevista_devolucion', models.DateField(verbose_name='Fecha Prevista de Devolucion')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vencido', 'Vencido'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado')], default='activo', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Acta de Prestamo',
                'verbose_name_plural': 'Actas de Prestamo',
                'ordering': ['-fecha_prestamo'],
            },
        ),
        migrations.AddField(
            model_name='devolucion',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.prestamo', verbose_name='Prestamo relacionado'),
        ),
        migrations.CreateModel(
            name='PrestamoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_entrega', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20, verbose_name='Estado de Entrega')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolucion')),
                ('estado_devolucion', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], max_length=20, null=True, verbose_name='Estado de Devolucion')),
                ('observaciones_devolucion', models.TextField(blank=True, verbose_name='Observaciones de Devolucion')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='Equipo')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='forms.prestamo', verbose_name='Prestamo')),
            ],
            options={
                'verbose_name': 'Detalle de Prestamo',
                'verbose_name_plural': 'Detalles de Prestamo',
            },
        ),
    ]
