# Generated by Django 6.0.5 on 2026-05-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='tipo_equipo',
            field=models.CharField(choices=[('pc', 'PC'), ('laptop', 'Laptop')], default='pc', max_length=10, verbose_name='Tipo de Equipo'),
        ),
        migrations.AddField(
            model_name='asignaciondetalle',
            name='componentes_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Componentes'),
        ),
    ]
