# Generated by Django 6.0.5 on 2026-05-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_asignacion_tipo_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondetalle',
            name='tipo_equipo',
            field=models.CharField(choices=[('pc', 'PC'), ('laptop', 'Laptop'), ('impresora', 'Impresora'), ('perifericos', 'Perifericos')], default='pc', max_length=20, verbose_name='Tipo de Equipo'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='tipo_equipo',
            field=models.CharField(choices=[('pc', 'PC'), ('laptop', 'Laptop'), ('impresora', 'Impresora'), ('perifericos', 'Perifericos')], default='pc', max_length=20, verbose_name='Tipo de Equipo'),
        ),
    ]
