# Generated by Django 6.0.5 on 2026-05-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cedula / DNI')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('departamento', models.CharField(max_length=150, verbose_name='Departamento')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
